# Generated by Django 6.0.7 on 2026-07-14 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(help_text='The content will be inserted directly into the page. It is VERY important that the HTML snippet is well-formed!', verbose_name='HTML')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='pages.page')),
            ],
            options={
                'verbose_name': 'HTML',
                'verbose_name_plural': 'HTML',
                'abstract': False,
            },
        ),
    ]
