# Generated by Django 6.0.7 on 2026-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=1000, verbose_name='caption'),
        ),
    ]
