# Generated by Django 6.0.7 on 2026-07-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='app_namespace',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='app instance namespace'),
        ),
        migrations.AddField(
            model_name='page',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='af', max_length=10, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='page',
            name='menu',
            field=models.CharField(blank=True, choices=[('', '')], default='main', max_length=100, verbose_name='menu'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('', '')], default='standard', max_length=100, verbose_name='page type'),
        ),
    ]
