# Generated by Django 6.0.7 on 2026-07-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_app_namespace_page_language_code_page_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language_code',
            field=models.CharField(choices=[('', '')], default='en', max_length=10, verbose_name='language'),
        ),
    ]
