# Generated by Django 6.0.7 on 2026-07-24 02:34

import feincms3.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, height_field='icon_height', upload_to=feincms3.utils.upload_to, verbose_name='icon', width_field='icon_width'),
        ),
        migrations.AddField(
            model_name='article',
            name='icon_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='icon_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='icon_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
